In [1]:
import numpy as np

In [3]:
#1. Create a null vector of size 10 but the fifth value which is 1.

ques_1=np.zeros(10,dtype=int)
ques_1[4]=1
print(ques_1)

#OR

ques_1=np.array([np.NaN]*10)
ques_1[4]=1
print(ques_1)

[0 0 0 0 1 0 0 0 0 0]
[nan nan nan nan  1. nan nan nan nan nan]


In [4]:
# 2. Create a vector with values ranging from 10 to 49.

ques_2=np.arange(10,49)
print(ques_2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [5]:
# 3. Create a 3x3 matrix with values ranging from 0 to 8

ques_3=np.matrix(np.arange(9))
ques_3=ques_3.reshape(3,3)
ques_3

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [6]:
ques_3=np.arange(9)
ques_3=ques_3.reshape(3,3)
ques_3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
# 4. Find indices of non-zero elements from [1,2,0,0,4,0]

ques_4=np.array([1,2,0,0,4,0])
np.where(ques_4!=0)

(array([0, 1, 4], dtype=int64),)

In [8]:
# 5. Create a 10x10 array with random values and find the minimum and maximum values.

ques_5=np.random.rand(100).reshape(10,10)
ques_5_min=ques_5.min()
ques_5_max=ques_5.max()
print('min value :',ques_5_min,'      max value :',ques_5_max)

min value : 0.017522284159900092       max value : 0.9858044591883462


In [9]:
#6. Create a random vector of size 30 and find the mean value.

ques_6=np.random.rand(30)
print(ques_6.mean())

0.453392867759298
